# Generated by Django 5.2 on 2025-04-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('Movie_name', models.CharField(max_length=50)),
                ('Ratings', models.FloatField(primary_key='Ratings', serialize=False)),
                ('Cast', models.CharField(max_length=50)),
                ('Release_year', models.DateField()),
                ('Genre', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
